### ISSUE TITLE
Project Dialog bug on not update to selected Structure!!

### ISSUE THREAD

**Issue by tws0002** [eoyilmaz/anima#24]
Hi Erkan,

I found a bug on Project Dialog about multiple Structure created!!
because I have a few projects created, and I have to assign the specific structure to the specified need.
but it seems not working!! it will assign the same structure for every project.
do u have this problem?

![anima_q_1](https://user-images.githubusercontent.com/7018625/42937242-03fa205e-8b81-11e8-8251-16bcf3e9f4f8.jpg)

Thanks
Desmond

**Comment by eoyilmaz** [comment]
You can not assign two *FilenameTemplate* objects to the same *Structure*
if they have the same *target_entity_type* value. Does it make sense?

Both the *SP_DF_Filename_Template* and *SP_Toei_Filename_Template* are
specific for *Task* instances (FilenameTemplate.target_entity_type =
"Task"). So if it was possible to set two FilenameTemplates with the same
target_entity_type value in one Structure, Stalker would not be able to
know which one to use. So Structure will allow only one FilenameTemplate
instance per target_entity_type.

Erkan Ozgur Yilmaz
VFX Supervisor & Photographer
www.youtube.com/erkanozguryilmaz

**Comment by tws0002** [comment]
Hi, 

I didn't assign 2 task *FilenameTemplate* at one structure!! I use the separate structure for specified *FilenameTemplate*. but it turns out the structure drop down tap didn't update to the selection I selected!!

because the different studio has a different structure and *FilenameTemplate*. so I need to created different structure. 

![am_s_q_v01](https://user-images.githubusercontent.com/7018625/43438484-fd479842-94c0-11e8-90d9-caba6db33510.jpg)
![am_t_s_q_v01](https://user-images.githubusercontent.com/7018625/43438482-f95d8836-94c0-11e8-9348-45315a5bffa5.jpg)
![am_d_s_q_v01](https://user-images.githubusercontent.com/7018625/43438483-fc22952a-94c0-11e8-95af-ca190b4aec40.jpg)

Thanks 
Desmond

**Comment by eoyilmaz** [comment]
I've checked the Structure comboBox and it is working fine. Do you still have any problems?

**Comment by eoyilmaz** [comment]
Please confirm that this is fixed in 3ecac5ad51730440899bf1889b48c492958dbc72.

**Comment by tws0002** [comment]
no is still the same the structure combobox is still not working!!

**Comment by eoyilmaz** [comment]
There should be some error messages printed in the script editor. Please
copy and paste it here.

Erkan Özgür Yılmaz
VFX Supervisor & Photographer
www.youtube.com/erkanozguryilmaz

**Comment by tws0002** [comment]
hi is there any way I can check the error?

**Comment by eoyilmaz** [comment]
This is fixed in 4395cb4665b80f249d33b13b20fe58276e16abb4
